### PR TITLE
test(scope): turn examples into test cases

### PR DESCRIPTION
**Pull request by yf-yang**

### CODE REVIEW

**Comment by yf-yang** [comment]
@dai-shi I found some test cases (even when I run them locally) are broken and suspect I can't directly import those examples because jotai-scope package resolution is incorrect? Do you have any suggestion?

**Comment by yf-yang** [comment]
Specifically, I'd like to know why examples can resolve to correct ScopeProvider in the repository, but the test cases can't.

**Comment by yf-yang** [comment]
Resolve by copy codes from examples.

I'm wondering if there is any way to share codes between examples and tests.

**Comment by dai-shi** [comment]
btw, I'm migrating to new setup: https://github.com/zustandjs/zustand-valtio/pull/2
I'll work on some repos in jotaijs, but for `jotai-scope` it's up to you, you can follow my setup, or do with your own setup.

> I'm wondering if there is any way to share codes between examples and tests.

It's also up to you, but my goal was to make examples standalone apps.
For example, this works: https://githubbox.com/jotaijs/jotai-scope/tree/main/examples/02_scope

**Review by dai-shi — APPROVED** [review]

**Pull request merged**
